adj1 = input('Give me an adjective: ')
noun1 = input('Now give me a noun: ')
verbpt1 = input('Now give me a verb, past-tense: ')
adverb1 = input('Now give me an adverb: ')
adj2 = input('Now give me another adjective: ')
noun2 = input('Now give me another noun: ')
noun3 = input('Now give me another noun: ')
adj3 = input('Now give me another adjective: ')
verb1 = input('Now give me a verb: ')
adverb2 = input('Now give me another adverb: ')
verbpt2 = input('Now give me another verb, past-tense: ')
adj4 = input('Lastly, give me one more adjective: ')


print('Today I went to the zoo.')
print('I saw a(n) ' + adj1 + ' ' + noun1 + ' jumping up and down in its tree.')
print('He ' + verbpt1 + ' ' + adverb1 + ' through the large tunnel that led to its ' + adj2 + ' ' + noun2 + '.')
print('I got some peanuts and passed them through the cage to a gigantic gray ' + noun3 + ' towering above my head.')
print('Feeding that animal made me hungry. I went to get a ' + adj3 + ' scoop of ice cream. It filled my stomach.')
print('Afterwards I had to ' + verb1 + ' ' + adverb2 + ' to catch our bus.')
print('When I got home I ' + verbpt2 + ' my mom for a ' + adj4 + ' day at the zoo.')
